
      const data = [
        {
          "Skin type": "Normal",
          "Concern": "Clear Acne & Breakouts",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Salicylic Acid (2%)• Niacinamide (5-10%)• Tea Tree Oil• Benzoyl Peroxide (2.5-5%)• Sulfur• Neem Extract• Turmeric Extract• Azeleic Acid",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "BHA toner or sulfur clay mask",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Reduce Oiliness & Shine",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Niacinamide (10%)• Kaolin Clay• Green Tea Extract• Witch Hazel• Hyaluronic Acid (lightweight)• Glycolic Acid• Salicylic Acid• Zinc PCA",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "Clay mask (kaolin or bentonite)",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Hydrate Dry Skin",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Hyaluronic Acid• Glycerin• Squalane• Ceramides• Shea Butter• Rosehip Oil• Aloe Vera• Honey• Panthenol",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "Sheet mask with hyaluronic acid",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Minimize Pores & Blackheads",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Salicylic Acid• Retinol (0.3-1%)• Niacinamide (10%)• Glycolic Acid• Clay (Bentonite/Kaolin)• AHAs• Charcoal• Vitamin C",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "BHA mask or gentle exfoliating scrub",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Even Out Skin Tone & Reduce Dark Spots",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Vitamin C (5-20%)• Alpha Arbutin• Tranexamic Acid• Kojic Acid• Niacinamide• Licorice Root Extract• Glycolic Acid• Azelaic Acid",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "Vitamin C mask or peel once a week",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Reduce Redness & Sensitivity",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Centella Asiatica (Cica)• Aloe Vera• Green Tea Extract• Ceramides• Colloidal Oatmeal• Panthenol• Allantoin• Bisabolol• Madecassoside",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "Aloe or Centella mask (calming)",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Anti-Aging: Reduce Wrinkles & Fine Lines",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Retinol/Retinoids• Peptides• Vitamin C• Hyaluronic Acid• Niacinamide• Coenzyme Q10• Bakuchiol• AHAs• Antioxidants",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "Peptide sheet mask or retinol cream (low %)*",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Improve Skin Firmness & Elasticity",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Peptides• Collagen• Elastin• Retinol• DMAE• Vitamin C• Hydrolyzed Protein• Amino Acids• Hyaluronic Acid",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "Firming gel mask with peptides",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Achieve a Natural Glow",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Vitamin C• Alpha Hydroxy Acids (AHAs)• Niacinamide• Hyaluronic Acid• Rosehip Oil• Antioxidants• Saffron Extract• Turmeric Extract",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "Enzyme exfoliant or glow sheet mask",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Clear Acne & Breakouts",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Salicylic Acid (2%)• Niacinamide (5-10%)• Tea Tree Oil• Benzoyl Peroxide (2.5-5%)• Sulfur• Neem Extract• Turmeric Extract• Azeleic Acid",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "BHA toner or sulfur clay mask",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Reduce Oiliness & Shine",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Niacinamide (10%)• Kaolin Clay• Green Tea Extract• Witch Hazel• Hyaluronic Acid (lightweight)• Glycolic Acid• Salicylic Acid• Zinc PCA",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "Clay mask (kaolin or bentonite)",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Hydrate Dry Skin",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Hyaluronic Acid• Glycerin• Squalane• Ceramides• Shea Butter• Rosehip Oil• Aloe Vera• Honey• Panthenol",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "Sheet mask with hyaluronic acid",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Minimize Pores & Blackheads",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Salicylic Acid• Retinol (0.3-1%)• Niacinamide (10%)• Glycolic Acid• Clay (Bentonite/Kaolin)• AHAs• Charcoal• Vitamin C",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "BHA mask or gentle exfoliating scrub",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Even Out Skin Tone & Reduce Dark Spots",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Vitamin C (5-20%)• Alpha Arbutin• Tranexamic Acid• Kojic Acid• Niacinamide• Licorice Root Extract• Glycolic Acid• Azelaic Acid",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "Vitamin C mask or peel once a week",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Reduce Redness & Sensitivity",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Centella Asiatica (Cica)• Aloe Vera• Green Tea Extract• Ceramides• Colloidal Oatmeal• Panthenol• Allantoin• Bisabolol• Madecassoside",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "Aloe or Centella mask (calming)",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Anti-Aging: Reduce Wrinkles & Fine Lines",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Retinol/Retinoids• Peptides• Vitamin C• Hyaluronic Acid• Niacinamide• Coenzyme Q10• Bakuchiol• AHAs• Antioxidants",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "Peptide sheet mask or retinol cream (low %)*",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Improve Skin Firmness & Elasticity",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Peptides• Collagen• Elastin• Retinol• DMAE• Vitamin C• Hydrolyzed Protein• Amino Acids• Hyaluronic Acid",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "Firming gel mask with peptides",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Achieve a Natural Glow",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Vitamin C• Alpha Hydroxy Acids (AHAs)• Niacinamide• Hyaluronic Acid• Rosehip Oil• Antioxidants• Saffron Extract• Turmeric Extract",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "Enzyme exfoliant or glow sheet mask",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Clear Acne & Breakouts",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
          "Essential Ingredients to Look For": "• Salicylic Acid (2%)• Niacinamide (5-10%)• Tea Tree Oil• Benzoyl Peroxide (2.5-5%)• Sulfur• Neem Extract• Turmeric Extract• Azeleic Acid",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "BHA toner or sulfur clay mask",
          "Other Suggestion": "Product under 300 each AND <br>Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Reduce Oiliness & Shine",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
          "Essential Ingredients to Look For": "• Niacinamide (10%)• Kaolin Clay• Green Tea Extract• Witch Hazel• Hyaluronic Acid (lightweight)• Glycolic Acid• Salicylic Acid• Zinc PCA",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "Clay mask (kaolin or bentonite)",
          "Other Suggestion": "Product under 300 each AND <br>Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Hydrate Dry Skin",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
          "Essential Ingredients to Look For": "• Hyaluronic Acid• Glycerin• Squalane• Ceramides• Shea Butter• Rosehip Oil• Aloe Vera• Honey• Panthenol",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "Sheet mask with hyaluronic acid",
          "Other Suggestion": "Product under 300 each AND <br>Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Minimize Pores & Blackheads",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
          "Essential Ingredients to Look For": "• Salicylic Acid• Retinol (0.3-1%)• Niacinamide (10%)• Glycolic Acid• Clay (Bentonite/Kaolin)• AHAs• Charcoal• Vitamin C",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "BHA mask or gentle exfoliating scrub",
          "Other Suggestion": "Product under 300 each AND <br>Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Even Out Skin Tone & Reduce Dark Spots",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
          "Essential Ingredients to Look For": "• Vitamin C (5-20%)• Alpha Arbutin• Tranexamic Acid• Kojic Acid• Niacinamide• Licorice Root Extract• Glycolic Acid• Azelaic Acid",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "Vitamin C mask or peel once a week",
          "Other Suggestion": "Product under 300 each AND <br>Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Reduce Redness & Sensitivity",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
          "Essential Ingredients to Look For": "• Centella Asiatica (Cica)• Aloe Vera• Green Tea Extract• Ceramides• Colloidal Oatmeal• Panthenol• Allantoin• Bisabolol• Madecassoside",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "Aloe or Centella mask (calming)",
          "Other Suggestion": "Product under 300 each AND <br>Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Anti-Aging: Reduce Wrinkles & Fine Lines",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
          "Essential Ingredients to Look For": "• Retinol/Retinoids• Peptides• Vitamin C• Hyaluronic Acid• Niacinamide• Coenzyme Q10• Bakuchiol• AHAs• Antioxidants",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "Peptide sheet mask or retinol cream (low %)*",
          "Other Suggestion": "Product under 300 each AND <br>Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Improve Skin Firmness & Elasticity",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
          "Essential Ingredients to Look For": "• Peptides• Collagen• Elastin• Retinol• DMAE• Vitamin C• Hydrolyzed Protein• Amino Acids• Hyaluronic Acid",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "Firming gel mask with peptides",
          "Other Suggestion": "Product under 300 each AND <br>Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Achieve a Natural Glow",
          "Commitment Level": "Minimal",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
          "Essential Ingredients to Look For": "• Vitamin C• Alpha Hydroxy Acids (AHAs)• Niacinamide• Hyaluronic Acid• Rosehip Oil• Antioxidants• Saffron Extract• Turmeric Extract",
          "Product Suggestion AM": "Facewash<br>Moisturiser<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Serum/ Moisturiser<br>",
          "Weekly Treatments": "Enzyme exfoliant or glow sheet mask",
          "Other Suggestion": "Product under 300 each AND <br>Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Clear Acne & Breakouts",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Salicylic Acid (2%)• Niacinamide (5-10%)• Tea Tree Oil• Benzoyl Peroxide (2.5-5%)• Sulfur• Neem Extract• Turmeric Extract• Azeleic Acid",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "BHA + Clay mask (alternate days)",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Reduce Oiliness & Shine",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Niacinamide (10%)• Kaolin Clay• Green Tea Extract• Witch Hazel• Hyaluronic Acid (lightweight)• Glycolic Acid• Salicylic Acid• Zinc PCA",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "Clay mask + light exfoliant (BHA or niacinamide)",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Hydrate Dry Skin",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Hyaluronic Acid• Glycerin• Squalane• Ceramides• Shea Butter• Rosehip Oil• Aloe Vera• Honey• Panthenol",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "Hydrating overnight mask + hyaluronic serum",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Minimize Pores & Blackheads",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Salicylic Acid• Retinol (0.3-1%)• Niacinamide (10%)• Glycolic Acid• Clay (Bentonite/Kaolin)• AHAs• Charcoal• Vitamin C",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "BHA + clay mask + pore-tightening toner",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Even Out Skin Tone & Reduce Dark Spots",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Vitamin C (5-20%)• Alpha Arbutin• Tranexamic Acid• Kojic Acid• Niacinamide• Licorice Root Extract• Glycolic Acid• Azelaic Acid",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "Vit C mask + AHA toner (on separate days)",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Reduce Redness & Sensitivity",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Centella Asiatica (Cica)• Aloe Vera• Green Tea Extract• Ceramides• Colloidal Oatmeal• Panthenol• Allantoin• Bisabolol• Madecassoside",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "Barrier-repair sleeping mask + oat or cica mask",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Anti-Aging: Reduce Wrinkles & Fine Lines",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Retinol/Retinoids• Peptides• Vitamin C• Hyaluronic Acid• Niacinamide• Coenzyme Q10• Bakuchiol• AHAs• Antioxidants",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "Retinol (1x/week) + firming peptide mask",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Improve Skin Firmness & Elasticity",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Peptides• Collagen• Elastin• Retinol• DMAE• Vitamin C• Hydrolyzed Protein• Amino Acids• Hyaluronic Acid",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "Collagen mask + facial massage roller",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Achieve a Natural Glow",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Vitamin C• Alpha Hydroxy Acids (AHAs)• Niacinamide• Hyaluronic Acid• Rosehip Oil• Antioxidants• Saffron Extract• Turmeric Extract",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "Exfoliating toner (AHA) + radiance sheet mask",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Clear Acne & Breakouts",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Salicylic Acid (2%)• Niacinamide (5-10%)• Tea Tree Oil• Benzoyl Peroxide (2.5-5%)• Sulfur• Neem Extract• Turmeric Extract• Azeleic Acid",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "BHA + Clay mask (alternate days)",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Reduce Oiliness & Shine",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Niacinamide (10%)• Kaolin Clay• Green Tea Extract• Witch Hazel• Hyaluronic Acid (lightweight)• Glycolic Acid• Salicylic Acid• Zinc PCA",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "Clay mask + light exfoliant (BHA or niacinamide)",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Hydrate Dry Skin",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Hyaluronic Acid• Glycerin• Squalane• Ceramides• Shea Butter• Rosehip Oil• Aloe Vera• Honey• Panthenol",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "Hydrating overnight mask + hyaluronic serum",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Minimize Pores & Blackheads",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Salicylic Acid• Retinol (0.3-1%)• Niacinamide (10%)• Glycolic Acid• Clay (Bentonite/Kaolin)• AHAs• Charcoal• Vitamin C",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "BHA + clay mask + pore-tightening toner",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Even Out Skin Tone & Reduce Dark Spots",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Vitamin C (5-20%)• Alpha Arbutin• Tranexamic Acid• Kojic Acid• Niacinamide• Licorice Root Extract• Glycolic Acid• Azelaic Acid",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "Vit C mask + AHA toner (on separate days)",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Reduce Redness & Sensitivity",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Centella Asiatica (Cica)• Aloe Vera• Green Tea Extract• Ceramides• Colloidal Oatmeal• Panthenol• Allantoin• Bisabolol• Madecassoside",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "Barrier-repair sleeping mask + oat or cica mask",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Anti-Aging: Reduce Wrinkles & Fine Lines",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Retinol/Retinoids• Peptides• Vitamin C• Hyaluronic Acid• Niacinamide• Coenzyme Q10• Bakuchiol• AHAs• Antioxidants",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "Retinol (1x/week) + firming peptide mask",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Improve Skin Firmness & Elasticity",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Peptides• Collagen• Elastin• Retinol• DMAE• Vitamin C• Hydrolyzed Protein• Amino Acids• Hyaluronic Acid",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "Collagen mask + facial massage roller",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Achieve a Natural Glow",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Vitamin C• Alpha Hydroxy Acids (AHAs)• Niacinamide• Hyaluronic Acid• Rosehip Oil• Antioxidants• Saffron Extract• Turmeric Extract",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "Exfoliating toner (AHA) + radiance sheet mask",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Clear Acne & Breakouts",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
          "Essential Ingredients to Look For": "• Salicylic Acid (2%)• Niacinamide (5-10%)• Tea Tree Oil• Benzoyl Peroxide (2.5-5%)• Sulfur• Neem Extract• Turmeric Extract• Azeleic Acid",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "BHA + Clay mask (alternate days)",
          "Other Suggestion": "Product under 300 each AND <br>Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Reduce Oiliness & Shine",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
          "Essential Ingredients to Look For": "• Niacinamide (10%)• Kaolin Clay• Green Tea Extract• Witch Hazel• Hyaluronic Acid (lightweight)• Glycolic Acid• Salicylic Acid• Zinc PCA",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "Clay mask + light exfoliant (BHA or niacinamide)",
          "Other Suggestion": "Product under 300 each AND <br>Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Hydrate Dry Skin",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
          "Essential Ingredients to Look For": "• Hyaluronic Acid• Glycerin• Squalane• Ceramides• Shea Butter• Rosehip Oil• Aloe Vera• Honey• Panthenol",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "Hydrating overnight mask + hyaluronic serum",
          "Other Suggestion": "Product under 300 each AND <br>Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Minimize Pores & Blackheads",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
          "Essential Ingredients to Look For": "• Salicylic Acid• Retinol (0.3-1%)• Niacinamide (10%)• Glycolic Acid• Clay (Bentonite/Kaolin)• AHAs• Charcoal• Vitamin C",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "BHA + clay mask + pore-tightening toner",
          "Other Suggestion": "Product under 300 each AND <br>Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Even Out Skin Tone & Reduce Dark Spots",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
          "Essential Ingredients to Look For": "• Vitamin C (5-20%)• Alpha Arbutin• Tranexamic Acid• Kojic Acid• Niacinamide• Licorice Root Extract• Glycolic Acid• Azelaic Acid",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "Vit C mask + AHA toner (on separate days)",
          "Other Suggestion": "Product under 300 each AND <br>Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Reduce Redness & Sensitivity",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
          "Essential Ingredients to Look For": "• Centella Asiatica (Cica)• Aloe Vera• Green Tea Extract• Ceramides• Colloidal Oatmeal• Panthenol• Allantoin• Bisabolol• Madecassoside",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "Barrier-repair sleeping mask + oat or cica mask",
          "Other Suggestion": "Product under 300 each AND <br>Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Anti-Aging: Reduce Wrinkles & Fine Lines",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
          "Essential Ingredients to Look For": "• Retinol/Retinoids• Peptides• Vitamin C• Hyaluronic Acid• Niacinamide• Coenzyme Q10• Bakuchiol• AHAs• Antioxidants",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "Retinol (1x/week) + firming peptide mask",
          "Other Suggestion": "Product under 300 each AND <br>Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Improve Skin Firmness & Elasticity",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
          "Essential Ingredients to Look For": "• Peptides• Collagen• Elastin• Retinol• DMAE• Vitamin C• Hydrolyzed Protein• Amino Acids• Hyaluronic Acid",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "Collagen mask + facial massage roller",
          "Other Suggestion": "Product under 300 each AND <br>Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Achieve a Natural Glow",
          "Commitment Level": "Moderate",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
          "Essential Ingredients to Look For": "• Vitamin C• Alpha Hydroxy Acids (AHAs)• Niacinamide• Hyaluronic Acid• Rosehip Oil• Antioxidants• Saffron Extract• Turmeric Extract",
          "Product Suggestion AM": "Facewash<br>Antioxidant serum (like Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Facewash<br>Treatment serum <br>(e.g., niacinamide, hyaluronic acid)<br>Moisturizer",
          "Weekly Treatments": "Exfoliating toner (AHA) + radiance sheet mask",
          "Other Suggestion": "Product under 300 each AND <br>Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Clear Acne & Breakouts",
          "Commitment Level": "Intensive",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Salicylic Acid (2%)• Niacinamide (5-10%)• Tea Tree Oil• Benzoyl Peroxide (2.5-5%)• Sulfur• Neem Extract• Turmeric Extract• Azeleic Acid",
          "Product Suggestion AM": "Facewash<br>Toner (hydrating/exfoliating)<br>Essence<br>Antioxidant serum (Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Cleanse<br>Toner<br>Active serum (AHA/BHA, retinol, peptides, etc.)<br>Hydrating serum (hyaluronic acid)<br>Moisturizer or sleeping mask",
          "Weekly Treatments": "BHA serum, clay mask, + salicylic acid peel (2x/mo)",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Reduce Oiliness & Shine",
          "Commitment Level": "Intensive",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Niacinamide (10%)• Kaolin Clay• Green Tea Extract• Witch Hazel• Hyaluronic Acid (lightweight)• Glycolic Acid• Salicylic Acid• Zinc PCA",
          "Product Suggestion AM": "Facewash<br>Toner (hydrating/exfoliating)<br>Essence<br>Antioxidant serum (Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Cleanse<br>Toner<br>Active serum (AHA/BHA, retinol, peptides, etc.)<br>Hydrating serum (hyaluronic acid)<br>Moisturizer or sleeping mask",
          "Weekly Treatments": "Oil-control enzyme mask, BHA toner, blotting essence",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Hydrate Dry Skin",
          "Commitment Level": "Intensive",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Hyaluronic Acid• Glycerin• Squalane• Ceramides• Shea Butter• Rosehip Oil• Aloe Vera• Honey• Panthenol",
          "Product Suggestion AM": "Facewash<br>Toner (hydrating/exfoliating)<br>Essence<br>Antioxidant serum (Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Cleanse<br>Toner<br>Active serum (AHA/BHA, retinol, peptides, etc.)<br>Hydrating serum (hyaluronic acid)<br>Moisturizer or sleeping mask",
          "Weekly Treatments": "HA mask, ceramide-rich sleeping pack, barrier repair mask",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Minimize Pores & Blackheads",
          "Commitment Level": "Intensive",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Salicylic Acid• Retinol (0.3-1%)• Niacinamide (10%)• Glycolic Acid• Clay (Bentonite/Kaolin)• AHAs• Charcoal• Vitamin C",
          "Product Suggestion AM": "Facewash<br>Toner (hydrating/exfoliating)<br>Essence<br>Antioxidant serum (Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Cleanse<br>Toner<br>Active serum (AHA/BHA, retinol, peptides, etc.)<br>Hydrating serum (hyaluronic acid)<br>Moisturizer or sleeping mask",
          "Weekly Treatments": "BHA serum, blackhead peel mask, niacinamide toner",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Even Out Skin Tone & Reduce Dark Spots",
          "Commitment Level": "Intensive",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Vitamin C (5-20%)• Alpha Arbutin• Tranexamic Acid• Kojic Acid• Niacinamide• Licorice Root Extract• Glycolic Acid• Azelaic Acid",
          "Product Suggestion AM": "Facewash<br>Toner (hydrating/exfoliating)<br>Essence<br>Antioxidant serum (Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Cleanse<br>Toner<br>Active serum (AHA/BHA, retinol, peptides, etc.)<br>Hydrating serum (hyaluronic acid)<br>Moisturizer or sleeping mask",
          "Weekly Treatments": "AHA peel, vitamin C serum, brightening enzyme mask",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Reduce Redness & Sensitivity",
          "Commitment Level": "Intensive",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Centella Asiatica (Cica)• Aloe Vera• Green Tea Extract• Ceramides• Colloidal Oatmeal• Panthenol• Allantoin• Bisabolol• Madecassoside",
          "Product Suggestion AM": "Facewash<br>Toner (hydrating/exfoliating)<br>Essence<br>Antioxidant serum (Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Cleanse<br>Toner<br>Active serum (AHA/BHA, retinol, peptides, etc.)<br>Hydrating serum (hyaluronic acid)<br>Moisturizer or sleeping mask",
          "Weekly Treatments": "Centella ampoule, azelaic acid cream, colloidal mask",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Anti-Aging: Reduce Wrinkles & Fine Lines",
          "Commitment Level": "Intensive",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Retinol/Retinoids• Peptides• Vitamin C• Hyaluronic Acid• Niacinamide• Coenzyme Q10• Bakuchiol• AHAs• Antioxidants",
          "Product Suggestion AM": "Facewash<br>Toner (hydrating/exfoliating)<br>Essence<br>Antioxidant serum (Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Cleanse<br>Toner<br>Active serum (AHA/BHA, retinol, peptides, etc.)<br>Hydrating serum (hyaluronic acid)<br>Moisturizer or sleeping mask",
          "Weekly Treatments": "Retinol (2–3x/week), peptide ampoule, collagen mask",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Improve Skin Firmness & Elasticity",
          "Commitment Level": "Intensive",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Peptides• Collagen• Elastin• Retinol• DMAE• Vitamin C• Hydrolyzed Protein• Amino Acids• Hyaluronic Acid",
          "Product Suggestion AM": "Facewash<br>Toner (hydrating/exfoliating)<br>Essence<br>Antioxidant serum (Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Cleanse<br>Toner<br>Active serum (AHA/BHA, retinol, peptides, etc.)<br>Hydrating serum (hyaluronic acid)<br>Moisturizer or sleeping mask",
          "Weekly Treatments": "Retinol, peptide ampoule, red light therapy (if available)",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Achieve a Natural Glow",
          "Commitment Level": "Intensive",
          "Preferred Skincare Ingredients/Products": "Natural/Organic Products",
          "Essential Ingredients to Look For": "• Vitamin C• Alpha Hydroxy Acids (AHAs)• Niacinamide• Hyaluronic Acid• Rosehip Oil• Antioxidants• Saffron Extract• Turmeric Extract",
          "Product Suggestion AM": "Facewash<br>Toner (hydrating/exfoliating)<br>Essence<br>Antioxidant serum (Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Cleanse<br>Toner<br>Active serum (AHA/BHA, retinol, peptides, etc.)<br>Hydrating serum (hyaluronic acid)<br>Moisturizer or sleeping mask",
          "Weekly Treatments": "AHA/BHA peel, glow serum, vitamin C ampoule",
          "Other Suggestion": "Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Clear Acne & Breakouts",
          "Commitment Level": "Intensive",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Salicylic Acid (2%)• Niacinamide (5-10%)• Tea Tree Oil• Benzoyl Peroxide (2.5-5%)• Sulfur• Neem Extract• Turmeric Extract• Azeleic Acid",
          "Product Suggestion AM": "Facewash<br>Toner (hydrating/exfoliating)<br>Essence<br>Antioxidant serum (Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Cleanse<br>Toner<br>Active serum (AHA/BHA, retinol, peptides, etc.)<br>Hydrating serum (hyaluronic acid)<br>Moisturizer or sleeping mask",
          "Weekly Treatments": "BHA serum, clay mask, + salicylic acid peel (2x/mo)",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Reduce Oiliness & Shine",
          "Commitment Level": "Intensive",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Niacinamide (10%)• Kaolin Clay• Green Tea Extract• Witch Hazel• Hyaluronic Acid (lightweight)• Glycolic Acid• Salicylic Acid• Zinc PCA",
          "Product Suggestion AM": "Facewash<br>Toner (hydrating/exfoliating)<br>Essence<br>Antioxidant serum (Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Cleanse<br>Toner<br>Active serum (AHA/BHA, retinol, peptides, etc.)<br>Hydrating serum (hyaluronic acid)<br>Moisturizer or sleeping mask",
          "Weekly Treatments": "Oil-control enzyme mask, BHA toner, blotting essence",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Hydrate Dry Skin",
          "Commitment Level": "Intensive",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Hyaluronic Acid• Glycerin• Squalane• Ceramides• Shea Butter• Rosehip Oil• Aloe Vera• Honey• Panthenol",
          "Product Suggestion AM": "Facewash<br>Toner (hydrating/exfoliating)<br>Essence<br>Antioxidant serum (Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Cleanse<br>Toner<br>Active serum (AHA/BHA, retinol, peptides, etc.)<br>Hydrating serum (hyaluronic acid)<br>Moisturizer or sleeping mask",
          "Weekly Treatments": "HA mask, ceramide-rich sleeping pack, barrier repair mask",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Minimize Pores & Blackheads",
          "Commitment Level": "Intensive",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Salicylic Acid• Retinol (0.3-1%)• Niacinamide (10%)• Glycolic Acid• Clay (Bentonite/Kaolin)• AHAs• Charcoal• Vitamin C",
          "Product Suggestion AM": "Facewash<br>Toner (hydrating/exfoliating)<br>Essence<br>Antioxidant serum (Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Cleanse<br>Toner<br>Active serum (AHA/BHA, retinol, peptides, etc.)<br>Hydrating serum (hyaluronic acid)<br>Moisturizer or sleeping mask",
          "Weekly Treatments": "BHA serum, blackhead peel mask, niacinamide toner",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Even Out Skin Tone & Reduce Dark Spots",
          "Commitment Level": "Intensive",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Vitamin C (5-20%)• Alpha Arbutin• Tranexamic Acid• Kojic Acid• Niacinamide• Licorice Root Extract• Glycolic Acid• Azelaic Acid",
          "Product Suggestion AM": "Facewash<br>Toner (hydrating/exfoliating)<br>Essence<br>Antioxidant serum (Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Cleanse<br>Toner<br>Active serum (AHA/BHA, retinol, peptides, etc.)<br>Hydrating serum (hyaluronic acid)<br>Moisturizer or sleeping mask",
          "Weekly Treatments": "AHA peel, vitamin C serum, brightening enzyme mask",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Reduce Redness & Sensitivity",
          "Commitment Level": "Intensive",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Centella Asiatica (Cica)• Aloe Vera• Green Tea Extract• Ceramides• Colloidal Oatmeal• Panthenol• Allantoin• Bisabolol• Madecassoside",
          "Product Suggestion AM": "Facewash<br>Toner (hydrating/exfoliating)<br>Essence<br>Antioxidant serum (Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Cleanse<br>Toner<br>Active serum (AHA/BHA, retinol, peptides, etc.)<br>Hydrating serum (hyaluronic acid)<br>Moisturizer or sleeping mask",
          "Weekly Treatments": "Centella ampoule, azelaic acid cream, colloidal mask",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Anti-Aging: Reduce Wrinkles & Fine Lines",
          "Commitment Level": "Intensive",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Retinol/Retinoids• Peptides• Vitamin C• Hyaluronic Acid• Niacinamide• Coenzyme Q10• Bakuchiol• AHAs• Antioxidants",
          "Product Suggestion AM": "Facewash<br>Toner (hydrating/exfoliating)<br>Essence<br>Antioxidant serum (Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Cleanse<br>Toner<br>Active serum (AHA/BHA, retinol, peptides, etc.)<br>Hydrating serum (hyaluronic acid)<br>Moisturizer or sleeping mask",
          "Weekly Treatments": "Retinol (2–3x/week), peptide ampoule, collagen mask",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Improve Skin Firmness & Elasticity",
          "Commitment Level": "Intensive",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Peptides• Collagen• Elastin• Retinol• DMAE• Vitamin C• Hydrolyzed Protein• Amino Acids• Hyaluronic Acid",
          "Product Suggestion AM": "Facewash<br>Toner (hydrating/exfoliating)<br>Essence<br>Antioxidant serum (Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Cleanse<br>Toner<br>Active serum (AHA/BHA, retinol, peptides, etc.)<br>Hydrating serum (hyaluronic acid)<br>Moisturizer or sleeping mask",
          "Weekly Treatments": "Retinol, peptide ampoule, red light therapy (if available)",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Achieve a Natural Glow",
          "Commitment Level": "Intensive",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly",
          "Essential Ingredients to Look For": "• Vitamin C• Alpha Hydroxy Acids (AHAs)• Niacinamide• Hyaluronic Acid• Rosehip Oil• Antioxidants• Saffron Extract• Turmeric Extract",
          "Product Suggestion AM": "Facewash<br>Toner (hydrating/exfoliating)<br>Essence<br>Antioxidant serum (Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Cleanse<br>Toner<br>Active serum (AHA/BHA, retinol, peptides, etc.)<br>Hydrating serum (hyaluronic acid)<br>Moisturizer or sleeping mask",
          "Weekly Treatments": "AHA/BHA peel, glow serum, vitamin C ampoule",
          "Other Suggestion": "Product under 300 each"
        },
        {
          "Skin type": "Normal",
          "Concern": "Clear Acne & Breakouts",
          "Commitment Level": "Intensive",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
          "Essential Ingredients to Look For": "• Salicylic Acid (2%)• Niacinamide (5-10%)• Tea Tree Oil• Benzoyl Peroxide (2.5-5%)• Sulfur• Neem Extract• Turmeric Extract• Azeleic Acid",
          "Product Suggestion AM": "Facewash<br>Toner (hydrating/exfoliating)<br>Essence<br>Antioxidant serum (Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Cleanse<br>Toner<br>Active serum (AHA/BHA, retinol, peptides, etc.)<br>Hydrating serum (hyaluronic acid)<br>Moisturizer or sleeping mask",
          "Weekly Treatments": "BHA serum, clay mask, + salicylic acid peel (2x/mo)",
          "Other Suggestion": "Product under 300 each AND <br>Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Reduce Oiliness & Shine",
          "Commitment Level": "Intensive",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
          "Essential Ingredients to Look For": "• Niacinamide (10%)• Kaolin Clay• Green Tea Extract• Witch Hazel• Hyaluronic Acid (lightweight)• Glycolic Acid• Salicylic Acid• Zinc PCA",
          "Product Suggestion AM": "Facewash<br>Toner (hydrating/exfoliating)<br>Essence<br>Antioxidant serum (Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Cleanse<br>Toner<br>Active serum (AHA/BHA, retinol, peptides, etc.)<br>Hydrating serum (hyaluronic acid)<br>Moisturizer or sleeping mask",
          "Weekly Treatments": "Oil-control enzyme mask, BHA toner, blotting essence",
          "Other Suggestion": "Product under 300 each AND <br>Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Hydrate Dry Skin",
          "Commitment Level": "Intensive",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
          "Essential Ingredients to Look For": "• Hyaluronic Acid• Glycerin• Squalane• Ceramides• Shea Butter• Rosehip Oil• Aloe Vera• Honey• Panthenol",
          "Product Suggestion AM": "Facewash<br>Toner (hydrating/exfoliating)<br>Essence<br>Antioxidant serum (Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Cleanse<br>Toner<br>Active serum (AHA/BHA, retinol, peptides, etc.)<br>Hydrating serum (hyaluronic acid)<br>Moisturizer or sleeping mask",
          "Weekly Treatments": "HA mask, ceramide-rich sleeping pack, barrier repair mask",
          "Other Suggestion": "Product under 300 each AND <br>Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Minimize Pores & Blackheads",
          "Commitment Level": "Intensive",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
          "Essential Ingredients to Look For": "• Salicylic Acid• Retinol (0.3-1%)• Niacinamide (10%)• Glycolic Acid• Clay (Bentonite/Kaolin)• AHAs• Charcoal• Vitamin C",
          "Product Suggestion AM": "Facewash<br>Toner (hydrating/exfoliating)<br>Essence<br>Antioxidant serum (Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Cleanse<br>Toner<br>Active serum (AHA/BHA, retinol, peptides, etc.)<br>Hydrating serum (hyaluronic acid)<br>Moisturizer or sleeping mask",
          "Weekly Treatments": "BHA serum, blackhead peel mask, niacinamide toner",
          "Other Suggestion": "Product under 300 each AND <br>Only Products where these 2 words - organic, cruelty free are mentioned"
        },
        {
          "Skin type": "Normal",
          "Concern": "Even Out Skin Tone & Reduce Dark Spots",
          "Commitment Level": "Intensive",
          "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
          "Essential Ingredients to Look For": "• Vitamin C (5-20%)• Alpha Arbutin• Tranexamic Acid• Kojic Acid• Niacinamide• Licorice Root Extract• Glycolic Acid• Azelaic Acid",
          "Product Suggestion AM": "Facewash<br>Toner (hydrating/exfoliating)<br>Essence<br>Antioxidant serum (Vitamin C)<br>Moisturizer<br>Sunscreen",
          "Product Suggestion PM": "Cleanse<br>Toner<br>Active serum (AHA/BHA, retinol, peptides, etc.)<br>Hydrating serum (hyaluronic acid)<br>Moisturizer or sleeping mask",
          "Weekly Treatments": "AHA peel, vitamin C serum, brightening enzyme mask",
          "Other Suggestion": "Product under 300 each AND <br>Only Products where these 2 words - organic, cruelty free are mentioned"
        },
  {
    "Skin type": "Normal",
    "Concern": "Even Out Skin Tone & Reduce Dark Spots",
    "Commitment Level": "Intensive",
    "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
    "Essential Ingredients to Look For": "Vitamin C (5-20%), Alpha Arbutin, Tranexamic Acid, Kojic Acid, Niacinamide, Licorice Root Extract, Glycolic Acid, Azelaic Acid",
    "Product Suggestion AM": "Facewash, Toner (hydrating/exfoliating), Essence, Antioxidant serum (Vitamin C), Moisturizer, Sunscreen",
    "Product Suggestion PM": "Cleanse, Toner, Active serum (AHA/BHA, retinol, peptides, etc.), Hydrating serum (hyaluronic acid), Moisturizer or sleeping mask",
    "Weekly Treatments": "AHA peel, vitamin C serum, brightening enzyme mask",
    "Other Suggestion": "Product under 300 each AND Only Products where these 2 words - organic, cruelty free are mentioned"
  },
  {
    "Skin type": "Normal",
    "Concern": "Reduce Redness & Sensitivity",
    "Commitment Level": "Intensive",
    "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
    "Essential Ingredients to Look For": "Centella Asiatica (Cica), Colloidal Oatmeal, Aloe Vera (99% pure), Chamomile Extract, Green Tea Extract, Panthenol, Allantoin, Bisabolol, Calendula, Cucumber Extract, Anti-inflammatory peptides",
    "Product Suggestion AM": "Facewash, Toner (hydrating/exfoliating), Essence, Antioxidant serum (Vitamin C), Moisturizer, Sunscreen",
    "Product Suggestion PM": "Cleanse, Toner, Active serum (AHA/BHA, retinol, peptides, etc.), Hydrating serum (hyaluronic acid), Moisturizer or sleeping mask",
    "Weekly Treatments": "Azelaic acid (low strength), oat/cica sleeping pack (3x/week)",
    "Other Suggestion": "Product under 300 each AND Only Products where these 2 words - organic, cruelty free are mentioned"
  },
  {
    "Skin type": "Normal",
    "Concern": "Anti-Aging: Reduce Wrinkles & Fine Lines",
    "Commitment Level": "Intensive",
    "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
    "Essential Ingredients to Look For": "Retinol/Retinoids, Peptides, Vitamin C, Hyaluronic Acid, Niacinamide, Coenzyme Q10, Bakuchiol, AHAs, Antioxidants",
    "Product Suggestion AM": "Facewash, Toner (hydrating/exfoliating), Essence, Antioxidant serum (Vitamin C), Moisturizer, Sunscreen",
    "Product Suggestion PM": "Cleanse, Toner, Active serum (AHA/BHA, retinol, peptides, etc.), Hydrating serum (hyaluronic acid), Moisturizer or sleeping mask",
    "Weekly Treatments": "Retinol (2–3x/week), peptide ampoule, collagen mask",
    "Other Suggestion": "Product under 300 each AND Only Products where these 2 words - organic, cruelty free are mentioned"
  },
  {
    "Skin type": "Normal",
    "Concern": "Improve Skin Firmness & Elasticity",
    "Commitment Level": "Intensive",
    "Preferred Skincare Ingredients/Products": "Budget-Friendly + Natural/Organic Products",
    "Essential Ingredients to Look For": "Peptides, Collagen, Elastin, Retinol, DMAE, Vitamin C, Hydrolyzed Protein, Amino Acids, Hyaluronic Acid",
    "Product Suggestion AM": "Facewash, Toner (hydrating/exfoliating), Essence, Antioxidant serum (Vitamin C), Moisturizer, Sunscreen",
    "Product Suggestion PM": "Cleanse, Toner, Active serum (AHA/BHA, retinol, peptides, etc.), Hydrating serum (hyaluronic acid), Moisturizer or sleeping mask",
    "Weekly Treatments": "Retinol, peptide ampoule, red light therapy (if available)",
    "Other Suggestion": "Product under 300 each AND Only Products where these 2 words - organic, cruelty free are mentioned"
  }
]
export default data;